from __future__ import annotations

import json
import re
import uuid
from datetime import datetime, timezone
from typing import Any

from google import genai
from google.genai import types
from sqlalchemy.orm import Session

from app.config import get_settings
from app.models import Node, Selection, SelectionItem
from app.store import get_generation_store
from app.schemas import TestCaseIdea


SYSTEM_PROMPT = """You are a medical-device QA engineer writing test-case IDEAS (not executable scripts)
for the CardioTrack CT-200 home blood pressure monitor.

Given selected manual sections, produce 3 to 5 concrete, repeatable QA test-case ideas.
Each test case must:
- have a clear title
- list numbered steps someone else could execute
- state an expected result tied to the source text
- cite source_node_keys from the provided nodes
- note residual risk if requirements are ambiguous

Return ONLY valid JSON matching this schema:
{
  "test_cases": [
    {
      "title": "string",
      "steps": ["string", "..."],
      "expected_result": "string",
      "source_node_keys": ["string"],
      "risk_notes": "string or null"
    }
  ]
}
Do not wrap in markdown fences. Do not include commentary outside JSON.
"""


def _build_user_payload(items: list[SelectionItem]) -> str:
    blocks = []
    for it in items:
        blocks.append(
            {
                "node_key": it.node_key,
                "heading": it.heading_snapshot,
                "content_hash": it.content_hash_snapshot,
                "body": it.body_snapshot,
            }
        )
    return json.dumps({"selected_nodes": blocks}, ensure_ascii=False, indent=2)


def _extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    return json.loads(text)


def _validate_cases(data: dict[str, Any]) -> list[TestCaseIdea]:
    raw = data.get("test_cases")
    if not isinstance(raw, list) or not raw:
        raise ValueError("Response missing non-empty test_cases list")
    cases = [TestCaseIdea.model_validate(c) for c in raw]
    if not (3 <= len(cases) <= 5):
        # Soft clamp policy: accept 1-8 but prefer 3-5; still require >=1
        if len(cases) < 1:
            raise ValueError("Need at least one test case")
    for c in cases:
        if not c.title or not c.steps or not c.expected_result:
            raise ValueError("Test case missing required fields")
    return cases


def _rule_based_fallback(user_payload: str) -> list[TestCaseIdea]:
    """Deterministic QA ideas when Gemini quota/API is unavailable.

    Still grounded in selection text so staleness hashing remains meaningful.
    Marked llm_status=fallback_rule_based by the caller.
    """
    data = json.loads(user_payload)
    nodes = data.get("selected_nodes") or []
    cases: list[TestCaseIdea] = []
    for node in nodes[:3]:
        heading = node.get("heading") or "Selected section"
        body = (node.get("body") or "")[:400]
        key = node.get("node_key") or "unknown"
        cases.append(
            TestCaseIdea(
                title=f"Verify behavior described in {heading}",
                steps=[
                    f"Open the CT-200 manual section '{heading}' ({key}).",
                    "Configure the device (or simulator) to the preconditions implied by the section.",
                    "Execute the primary action/condition described in the section text.",
                    "Observe displayed codes, timings, and safety responses.",
                ],
                expected_result=(
                    f"Device behavior matches the normative statements in '{heading}'. "
                    f"Evidence excerpt: {body[:180]}..."
                ),
                source_node_keys=[key],
                risk_notes="Generated by rule-based fallback because the LLM provider was unavailable/quota-exhausted.",
            )
        )
    while len(cases) < 3 and nodes:
        n0 = nodes[0]
        cases.append(
            TestCaseIdea(
                title=f"Negative / boundary check for {n0.get('heading')}",
                steps=[
                    "Identify numeric thresholds or error codes in the selected text.",
                    "Drive the system just below, at, and above each threshold (or inject the error condition).",
                    "Record pass/fail against the expected device response.",
                ],
                expected_result="Boundary outcomes match the manual; safety paths (e.g. overpressure) cannot be silenced if stated.",
                source_node_keys=[n0.get("node_key") or "unknown"],
                risk_notes="Fallback case — replace with LLM output when quota is available.",
            )
        )
    return cases[:5]


def call_gemini_with_retries(user_payload: str, max_attempts: int = 3) -> tuple[list[TestCaseIdea], str]:
    """Returns (cases, status). status is ok|repaired|fallback_rule_based."""
    settings = get_settings()
    if not settings.gemini_api_key:
        return _rule_based_fallback(user_payload), "fallback_rule_based"

    client = genai.Client(api_key=settings.gemini_api_key)
    models_to_try = [
        settings.gemini_model,
        "gemini-2.5-flash",
        "gemini-2.0-flash-lite",
        "gemini-1.5-flash",
        "gemini-flash-latest",
    ]
    # de-dupe preserving order
    seen: set[str] = set()
    models: list[str] = []
    for m in models_to_try:
        if m and m not in seen:
            seen.add(m)
            models.append(m)

    last_error = None
    raw_text = ""
    quota_hit = False

    for model in models:
        for attempt in range(1, max_attempts + 1):
            repair_hint = ""
            if attempt > 1:
                repair_hint = (
                    f"\n\nPrevious response was invalid ({last_error}). "
                    "Return ONLY corrected JSON for the schema. No markdown."
                )
            try:
                response = client.models.generate_content(
                    model=model,
                    contents=SYSTEM_PROMPT + "\n\nSOURCE NODES:\n" + user_payload + repair_hint,
                    config=types.GenerateContentConfig(
                        temperature=0.2,
                        response_mime_type="application/json",
                    ),
                )
                raw_text = response.text or ""
                data = _extract_json(raw_text)
                cases = _validate_cases(data)
                status = "ok" if attempt == 1 else "repaired"
                return cases, status
            except Exception as exc:  # noqa: BLE001 — intentional: LLM/parse failures
                last_error = f"[{model}] {exc}"
                if "RESOURCE_EXHAUSTED" in str(exc) or "429" in str(exc):
                    quota_hit = True
                    break  # try next model

    if quota_hit or last_error:
        # Keep the pipeline demoable; never return empty generations.
        return _rule_based_fallback(user_payload), "fallback_rule_based"

    raise RuntimeError(f"LLM output invalid after retries: {last_error}\nRaw: {raw_text[:500]}")

def generate_for_selection(db: Session, selection_id: int, force: bool = False) -> dict[str, Any]:
    selection = db.query(Selection).filter(Selection.id == selection_id).one_or_none()
    if selection is None:
        raise LookupError(f"Selection {selection_id} not found")

    coll = get_generation_store()
    if not force:
        existing = coll.find_one(
            {"selection_id": selection_id, "llm_status": {"$in": ["ok", "repaired", "fallback_rule_based"]}}
        )
        if existing:
            existing["id"] = str(existing["_id"])
            return _serialize_generation(existing)

    items = db.query(SelectionItem).filter(SelectionItem.selection_id == selection_id).all()
    if not items:
        raise ValueError("Selection has no nodes")

    payload = _build_user_payload(items)
    cases, status = call_gemini_with_retries(payload)

    source_hashes = {it.node_key: it.content_hash_snapshot for it in items}
    doc = {
        "_id": str(uuid.uuid4()),
        "selection_id": selection.id,
        "selection_name": selection.name,
        "version_id": selection.version_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "test_cases": [c.model_dump() for c in cases],
        "source_hashes": source_hashes,
        "source_nodes": [
            {
                "node_id": it.node_id,
                "node_key": it.node_key,
                "heading": it.heading_snapshot,
                "content_hash": it.content_hash_snapshot,
                "version_number": it.version_number,
            }
            for it in items
        ],
        "llm_status": status,
    }
    coll.insert_one(doc)
    return _serialize_generation(doc)


def _serialize_generation(doc: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": str(doc.get("_id")),
        "selection_id": doc["selection_id"],
        "selection_name": doc["selection_name"],
        "created_at": doc["created_at"],
        "test_cases": doc["test_cases"],
        "source_hashes": doc["source_hashes"],
        "llm_status": doc["llm_status"],
        "source_nodes": doc.get("source_nodes", []),
        "version_id": doc.get("version_id"),
    }


def assess_staleness(db: Session, generation: dict[str, Any], against_latest: bool = True) -> dict[str, Any]:
    """Compare generation source hashes to current document nodes with same node_key.

    Limit: any hash change (including trivial wording) is flagged the same as a
    clinical threshold change — we do not semantically grade severity.
    """
    settings_note = (
        "Staleness is hash-based equality on pinned source text. A one-word wording "
        "change is treated the same as a changed pressure threshold. We do not auto-regenerate."
    )
    from app.models import DocumentVersion
    from app.config import get_settings

    settings = get_settings()
    doc = db.query(__import__("app.models", fromlist=["Document"]).Document).filter_by(
        slug=settings.document_slug
    ).one_or_none()

    latest_version = None
    if doc:
        latest_version = (
            db.query(DocumentVersion)
            .filter(DocumentVersion.document_id == doc.id)
            .order_by(DocumentVersion.version_number.desc())
            .first()
        )

    changed: list[dict[str, Any]] = []
    if latest_version is None:
        return {
            "generation_id": str(generation.get("id") or generation.get("_id")),
            "selection_id": generation["selection_id"],
            "is_stale": False,
            "compared_against_version": None,
            "changed_nodes": [],
            "limits_note": settings_note,
        }

    current_nodes = {
        n.node_key: n
        for n in db.query(Node).filter(Node.version_id == latest_version.id).all()
    }

    for key, old_hash in (generation.get("source_hashes") or {}).items():
        cur = current_nodes.get(key)
        if cur is None:
            changed.append({"node_key": key, "reason": "removed_or_unmatched_in_latest", "old_hash": old_hash})
        elif cur.content_hash != old_hash:
            changed.append(
                {
                    "node_key": key,
                    "reason": "content_hash_mismatch",
                    "old_hash": old_hash,
                    "new_hash": cur.content_hash,
                    "heading": cur.heading,
                }
            )

    return {
        "generation_id": str(generation.get("id") or generation.get("_id")),
        "selection_id": generation["selection_id"],
        "is_stale": len(changed) > 0,
        "compared_against_version": latest_version.version_number,
        "changed_nodes": changed,
        "limits_note": settings_note,
    }
